apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: go-mail-api-namespace
  labels:
    app: postgres
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: adminpassword
  POSTGRES_DB: maildatabase
  POSTGRES_HOST: postgres-headless.postgres-namespace.svc.cluster.local
  POSTGRES_PORT: "5432"