apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-mail-api-hpa
  namespace: go-mail-api-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-mail-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
