name: CD

on: 
  push:
    branches: ["main"]
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request'}}
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: | 
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

#    - name: Setup Kustomize
#      uses: imranismail/setup-kustomize@v2
#      with: 
#        kustomize-version: "5.6.3"
#
#    - name: Update Kubernetes resources
#      env:
#        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#        IMAGE_NAME: ${{ vars.IMAGE_NAME }}
#      run: |
#        cd k8s
#        kustomize edit set image go-mail-api-app-image=$DOCKERHUB_USERNAME/$IMAGE_NAME:$GITHUB_SHA
#
#    - name: Commit and Push
#      run: |
#        git config --local user.name "github-actions[bot]"
#        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
#        git commit -am "Bump docker version"
#        git push
